[window]
padding = { x = 4, y = 2 }

[font]
size = 12.0
offset = { x = 1, y = 2 }
normal = { family = "HackGen Console NF", style="Regular" }
bold = { family = "HackGen Console NF", style="Bold" }
italic = { family = "HackGen Console NF", style="Italic" }
bold_italic = { family = "HackGen Console NF", style="Bold Italic" }
